image: node:22-slim
##############
# Use =>
#   stage:
#   image:
#   services:
#   needs:
#   extends:
#   before_script:
#   script:
#   after_script:

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PNPM_HOME: $CI_PROJECT_DIR/.pnpm-store
  DB_HOST: "eggo-devdb"
  DB_PORT: 3306
  DB_USER: "kanadbuser"
  DB_PASSWORD: "dev-pass"
  DB_NAME: "kanaliiga"
  TRIVY_VERSION: "0.59.1" # Set the Trivy version here
  TRIVY_SEVERITY: "HIGH,CRITICAL,MEDIUM"

# Define a common anchor for the cache configuration
.common-cache: &common-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pnpm-store
      - node_modules/
      - packages/
      - apps/frontend/node_modules/
      - apps/backend/node_modules/

.default:
  before_script:
    - npm install -g pnpm
  <<: *common-cache # Include the common cache configuration

# Sadly gitlab changes do not support with anchors or references to make these DRY
.frontend-changes: &frontend-changes
  changes:
    - "package.json"
    - "pnpm-*.yaml"
    - ".gitlab-ci.yml"
    - "packages/**/*"
    - "apps/frontend/**/*"

.backend-changes: &backend-changes
  changes:
    - "package.json"
    - "pnpm-*.yaml"
    - ".gitlab-ci.yml"
    - "packages/**/*"
    - "apps/backend/**/*"

.all-app-changes: &all-app-changes
  changes:
    - "package.json"
    - "turbo.json"
    - "pnpm-*.yaml"
    - ".gitlab-ci.yml"
    - "packages/**/*"
    - "apps/{frontend,backend}/**/*"

# These either cant be DRY because the rules are OR and not AND (the - & anchors do not work really well)
.main-frontend:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      <<: *frontend-changes

.main-backend:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      <<: *backend-changes

.main-all-app:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      <<: *all-app-changes

.mr-frontend:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      <<: *frontend-changes

.mr-backend:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      <<: *backend-changes

.mr-all-app:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      <<: *all-app-changes

# Define the pull-only cache configuration
.pull-only-cache:
  <<: *common-cache # Merge the common cache configuration
  cache:
    policy: pull # Add the pull policy

# Define common configurations using anchors
.common-docker-build: &common-docker-build
  stage: build-docker
  image: docker:stable
  services:
    - docker:dind
  cache:
    paths:
      - .trivycache/
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
    - apk update && apk add jq

.common-docker-scan: &common-docker-scan
  script: &docker-scan-script
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA . -f $DOCKERFILE_DEV
    - docker build -t $CI_REGISTRY/$IMAGE_NAME . -f $DOCKERFILE
    - ./trivy image --exit-code 0 --scanners vuln --severity ${TRIVY_SEVERITY} --format template --template "@contrib/gitlab-codequality.tpl" -o gl-codeclimate-image-$IMAGE_NAME.json $CI_REGISTRY/$IMAGE_NAME
    - ./trivy filesystem --scanners misconfig,vuln --exit-code 0 --severity ${TRIVY_SEVERITY} --format template --template "@contrib/gitlab-codequality.tpl" -o gl-codeclimate-fs-$IMAGE_NAME.json .
  artifacts: &docker-scan-artifacts
    paths:
      - gl-codeclimate-image-$IMAGE_NAME.json
      - gl-codeclimate-fs-$IMAGE_NAME.json

stages:
  - install
  - lint
  - security
  - test
  - build
  - build-docker
  # - post-build
  - deploy

install:
  stage: install
  extends: [.default, .mr-all-app]
  script:
    - pnpm install

check-types:
  stage: lint
  extends: [.default, .pull-only-cache, .mr-all-app]
  script:
    - pnpm check-types

lint:frontend:
  stage: lint
  extends: [.default, .pull-only-cache, .mr-frontend]
  script:
    - pnpm --filter=frontend lint

lint:backend:
  stage: lint
  extends: [.default, .pull-only-cache, .mr-backend]
  script:
    - pnpm --filter=backend lint

audit:
  stage: security
  extends: [.default, .pull-only-cache, .mr-all-app]
  allow_failure: true
  script:
    - pnpm audit --json > gl-dependency-scanning-report.json || true
    - apt update && apt install -y jq
    - ./scripts/audit.sh
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning.json
    paths:
      - gl-dependency-scanning.json

secrets_scan:
  stage: security
  image: python:3.9
  extends: [.mr-all-app]
  script:
    - pip install trufflehog
    - trufflehog --regex --entropy=False .
  allow_failure: true

test:backend:
  stage: test
  extends: [.pull-only-cache, .default, .mr-backend]
  services:
    - name: bitnami/mariadb:11.4.2
      alias: eggo-devdb
    - name: redis:7-alpine
      alias: eggo-redis
  variables:
    MARIADB_ROOT_PASSWORD: dev-pass
    MARIADB_USER: kanadbuser
    MARIADB_PASSWORD: dev-pass
    MARIADB_DATABASE: kanaliiga
    MARIADB_MAX_ALLOWED_PACKET: 128M
    MARIADB_INNODB_LOG_FILE_SIZE: 64M
    REDIS_HOST: eggo-redis
    REDIS_PORT: 6379
  before_script:
    - npm install -g pnpm
    - export $(grep -v '^#' .env.base | xargs)
    - pnpm --filter=backend migrate
    - pnpm --filter=backend seed
  script:
    - pnpm --filter=backend test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      junit:
        - apps/backend/test-results/junit/results.xml
      coverage_report:
        coverage_format: cobertura
        path: apps/backend/coverage/cobertura-coverage.xml
    paths:
      - apps/backend/test-results/junit/results.xml
      - apps/backend/coverage/cobertura-coverage.xml

build:frontend:
  stage: build
  extends: [.pull-only-cache, .default, .mr-frontend]
  script:
    - pnpm --filter=frontend build

build:backend:
  stage: build
  extends: [.pull-only-cache, .default, .mr-backend]
  script:
    - pnpm --filter=backend build

# Backend job
build-dockerfile:backend:
  extends: [.pull-only-cache, .mr-backend]
  <<: *common-docker-build
  variables:
    IMAGE_NAME: eggo-backend
    DOCKERFILE_DEV: apps/backend/Dockerfile.dev
    DOCKERFILE: apps/backend/Dockerfile
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  script: *docker-scan-script
  artifacts: *docker-scan-artifacts

# Frontend job
build-dockerfile:frontend:
  extends: [.pull-only-cache, .mr-frontend]
  <<: *common-docker-build
  variables:
    IMAGE_NAME: eggo-frontend
    DOCKERFILE_DEV: apps/frontend/Dockerfile.dev
    DOCKERFILE: apps/frontend/Dockerfile
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  script: *docker-scan-script
  artifacts: *docker-scan-artifacts

push-dockerfile:backend:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  extends: [.main-backend]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend . -f apps/backend/Dockerfile
    - docker push $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend

push-dockerfile:frontend:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  extends: [.main-frontend]
  variables:
    NEXT_PUBLIC_API_URL: $HUBBE_PUBLIC_URL
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg NEXT_PUBLIC_API_URL=https://$NEXT_PUBLIC_API_URL -t $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-frontend . -f apps/frontend/Dockerfile
    - docker push $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-frontend

# Manual jobs for merge requests
push-dockerfile:backend:dev:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend:dev . -f apps/backend/Dockerfile
    - docker push $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend:dev
    - docker build -t $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend:devseed . -f apps/backend/Dockerfile.dev
    - docker push $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-backend:devseed

push-dockerfile:frontend:dev:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  variables:
    NEXT_PUBLIC_API_URL: $HUBBEDEV_PUBLIC_URL
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg NEXT_PUBLIC_API_URL=https://$NEXT_PUBLIC_API_URL -t $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-frontend:dev . -f apps/frontend/Dockerfile
    - docker push $CI_REGISTRY/kanaliiga_public/kanahub/eggosystem/eggo-frontend:dev

# Combine artifacts job
# Disabled for now due pipeline fixing
# combine-codequality-reports:
#   stage: post-build
#   image: alpine:latest
#   extends: [.mr-all-app]
#   needs:
#     - job: build-dockerfile:backend
#       artifacts: true
#     - job: build-dockerfile:frontend
#       artifacts: true
#   script:
#     - apk add jq
#     - jq -s 'add' gl-codeclimate-image-eggo-backend.json gl-codeclimate-fs-eggo-backend.json gl-codeclimate-image-eggo-frontend.json gl-codeclimate-fs-eggo-frontend.json > gl-codeclimate.json
#   artifacts:
#     paths:
#       - gl-codeclimate.json
#     reports:
#       codequality: gl-codeclimate.json

deploy:
  image: alpine:latest
  stage: deploy
  extends: [.main-all-app]
  environment:
    name: production # This enables GitLab Environments
    url: https://${HUB_PUBLIC_URL}
  variables:
    MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    MARIADB_USER: $MARIADB_USER
    MARIADB_PASSWORD: $MARIADB_PASSWORD
    MARIADB_DATABASE: $MARIADB_DATABASE
    DB_HOST: $DB_HOST
    DB_PORT: $DB_PORT
    DB_USER: $DB_USER
    DB_PASSWORD: $DB_PASSWORD
    DB_NAME: $DB_NAME
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    PROD_SERVER_IP: $PROD_SERVER_IP
    STEAM_API_KEY: $STEAM_API_KEY
    PHPMYADMIN_AUTH_BASE64: $PHPMYADMIN_AUTH_BASE64
  before_script:
    - "which ssh-agent || ( apk update -q && apk add openssh-client gettext rsync -q )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export PHPMYADMIN_AUTH=$(echo $PHPMYADMIN_AUTH_BASE64 | base64 -d)
    - envsubst < docker-compose.prod.yml > docker-compose.prod.subst.yml
    - rsync -v ./docker-compose.prod.subst.yml kanaliiga@$PROD_SERVER_IP:~/docker/eggosystem/docker-compose.yml
    - ssh kanaliiga@$PROD_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem/docker-compose.yml pull"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem/docker-compose.yml up -d"

deploy-dev:
  image: alpine:latest
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  needs:
    - job: push-dockerfile:frontend:dev
    - job: push-dockerfile:backend:dev
  environment:
    name: development
    url: https://${HUB_DEV_PUBLIC_URL}
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    PROD_SERVER_IP: $PROD_SERVER_IP
    STEAM_API_KEY: $STEAM_API_KEY
  before_script:
    - "which ssh-agent || ( apk update -q && apk add openssh-client gettext rsync -q )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - envsubst < docker-compose.dev.yml > docker-compose.dev.subst.yml
    - rsync -v ./docker-compose.dev.subst.yml kanaliiga@$PROD_SERVER_IP:~/docker/eggosystem-dev/docker-compose.yml
    - ssh kanaliiga@$PROD_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem-dev/docker-compose.yml pull"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem-dev/docker-compose.yml up -d"

seed-dev:
  image: alpine:latest
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  needs:
    - job: push-dockerfile:backend:dev
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    PROD_SERVER_IP: $PROD_SERVER_IP
  before_script:
    - "which ssh-agent || ( apk update -q && apk add openssh-client gettext rsync -q )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh kanaliiga@$PROD_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem-dev/docker-compose.yml pull"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem-dev/docker-compose.yml --profile migrate up -d"
    - ssh kanaliiga@$PROD_SERVER_IP "docker compose -f ~/docker/eggosystem-dev/docker-compose.yml --profile seed up -d"
