services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:${ENV_ID}
    pull_policy: always
    depends_on:
      seed:
        condition: service_completed_successfully
      eggo-redis:
        condition: service_started
    environment:
      NODE_ENV: production
      DB_HOST: eggo-devdb-${ENV_ID}
      DB_USER: "ondemand_${ENV_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: kanaliiga
      DB_PORT: 3306
      BASE_PATH: "/${ENV_ID}"
      FRONTEND_URL: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}
      BACKEND_URL: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}
      REDIS_HOST: eggo-redis-${ENV_ID}
      REDIS_PORT: 6379
      STEAM_API_KEY: $STEAM_API_KEY
      FACEIT_API_KEY: $FACEIT_API_KEY
      JWT_SECRET: $JWT_SECRET_ONDEMAND
      JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET_ONDEMAND
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      JWT_REFRESH_EXPIRES_IN: $JWT_REFRESH_EXPIRES_IN
      OTEL_SERVICE_NAME: eggosystem-mr-${ENV_ID}-backend-1
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=ondemand,service.namespace=eggosystem,service.version=1.0.0.0,service.instance.id=backend-${ENV_ID}"
      PRIVACY_POLICY_VERSION: $PRIVACY_POLICY_VERSION
      SMTP_HOST: $SMTP_HOST
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
    networks:
      web:
        aliases:
          - hubbe-${ENV_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbe-${ENV_ID}.entrypoints=http"
      - "traefik.http.routers.hubbe-${ENV_ID}.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}/api/v1`)"
      - "traefik.http.middlewares.hubbe-${ENV_ID}-strip.stripprefix.prefixes=/${ENV_ID}"
      - "traefik.http.routers.hubbe-${ENV_ID}.middlewares=hubbe-${ENV_ID}-strip"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.entrypoints=https"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}/api/v1`)"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.middlewares=hubbe-${ENV_ID}-strip"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.tls=true"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbe-${ENV_ID}-secure.service=hubbe-${ENV_ID}"
      - "traefik.http.services.hubbe-${ENV_ID}.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend:${ENV_ID}
    pull_policy: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}
      NEXT_PUBLIC_CLIENT_API_URL: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}
      NEXT_PUBLIC_BASE_PATH: /${ENV_ID}
      NEXT_PUBLIC_BASE_URL: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}
    networks:
      web:
        aliases:
          - kanahub-${ENV_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahub-${ENV_ID}.entrypoints=http"
      - "traefik.http.routers.kanahub-${ENV_ID}.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}`)"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.entrypoints=https"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}`)"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.tls=true"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahub-${ENV_ID}-secure.service=kanahub-${ENV_ID}"
      - "traefik.http.services.kanahub-${ENV_ID}.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

  eggo-devdb-${ENV_ID}:
    image: bitnami/mariadb:11.4.2
    restart: always
    container_name: eggo-devdb-${ENV_ID}
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "ondemand_${ENV_ID}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: kanaliiga
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MARIADB_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - /home/kanaliiga/docker/eggosystem-staging/my.cnf:/opt/bitnami/mariadb/conf/my.cnf

  eggo-redis:
    image: redis:7-alpine
    restart: always
    container_name: eggo-redis-${ENV_ID}
    networks:
      - web

  seed:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-migrations:${ENV_ID}
    depends_on:
      eggo-devdb-${ENV_ID}:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: eggo-devdb-${ENV_ID}
      DB_USER: "ondemand_${ENV_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: kanaliiga
      DB_PORT: 3306
    command: pnpm --filter=backend seed
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      eggo-devdb-${ENV_ID}:
        condition: service_healthy
    environment:
      PMA_HOST: eggo-devdb-${ENV_ID}
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      PMA_ABSOLUTE_URI: https://${HUBDEV_PUBLIC_URL}/${ENV_ID}/phpmyadmin/
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}.entrypoints=http"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}/phpmyadmin/`)"
      - "traefik.http.middlewares.hubphpmyadmin-${ENV_ID}-auth.basicauth.users=${PHPMYADMIN_AUTH}"
      - "traefik.http.middlewares.hubphpmyadmin-${ENV_ID}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.hubphpmyadmin-${ENV_ID}-stripprefix.stripprefix.prefixes=/${ENV_ID}/phpmyadmin"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}.middlewares=hubphpmyadmin-${ENV_ID}-https-redirect"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.entrypoints=https"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/${ENV_ID}/phpmyadmin/`)"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.tls=true"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.priority=100"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}.priority=100"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.middlewares=hubphpmyadmin-${ENV_ID}-stripprefix,hubphpmyadmin-${ENV_ID}-auth"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.tls.certresolver=http"
      - "traefik.http.routers.hubphpmyadmin-${ENV_ID}-secure.service=hubphpmyadmin-${ENV_ID}"
      - "traefik.http.services.hubphpmyadmin-${ENV_ID}.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
    name: web
