x-phpmyadmin: &phpmyadmin
  image: phpmyadmin/phpmyadmin:5.2.2
  depends_on:
    eggo-devdb:
      condition: service_healthy
  restart: always
  env_file: .env.development

services:
  backend:
    image: eggo-back
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      eggo-devdb:
        condition: service_healthy
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src
      - ./packages/types:/usr/src/app/packages/types
      - ./apps/backend/private_access_token.pem:/usr/src/app/apps/backend/private_access_token.pem
      - ./apps/backend/public_access_token.pem:/usr/src/app/apps/backend/public_access_token.pem
      - ./apps/backend/private_refresh_token.pem:/usr/src/app/apps/backend/private_refresh_token.pem
      - ./apps/backend/public_refresh_token.pem:/usr/src/app/apps/backend/public_refresh_token.pem
    env_file: .env.development
    environment:
      - BACKEND_SERVICE_API_KEY=local_development_key
    command: "pnpm --filter=backend dev"

  seed:
    image: eggo-back
    profiles:
      - seed
      - test
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    env_file: .env.development
    command: "pnpm --filter=backend seed"

  frontend:
    image: eggo-front
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - NEXT_PUBLIC_CLIENT_API_URL=http://localhost:3001
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    volumes:
      - ./apps/frontend/src:/usr/src/app/apps/frontend/src # Mount source code for live reloading
      - ./apps/frontend/public:/usr/src/app/apps/frontend/public # Mount source code for live reloading
      - ./apps/frontend/node_modules:/usr/src/app/apps/frontend/node_modules # Mount source code for live reloading
      - ./packages/types:/usr/src/app/packages/types
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: "pnpm --filter=frontend dev"

  eggo-redis:
    image: redis:8-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

  eggo-rabbitmq:
    image: rabbitmq:4.1-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - 15673:15672 # Management UI port (shifted to avoid conflicts)

  eggo-phpmyadmin:
    <<: *phpmyadmin
    ports:
      - 8082:80

  eggo-phpmyadmin-dev:
    <<: *phpmyadmin
    profiles:
      - dev

  eggo-devdb:
    image: bitnami/mariadb:11.7.2
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=dev-pass
      - MARIADB_USER=kanadbuser
      - MARIADB_PASSWORD=dev-pass
      - MARIADB_DATABASE=kanaliiga
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - ./conf/mariadb/my.cnf:/opt/bitnami/mariadb/conf/my.cnf

  migrations:
    image: eggo-migrations
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.migrations.dev
    profiles:
      - migrations
    depends_on:
      eggo-devdb:
        condition: service_healthy
    environment:
      WAIT_FOR_DB: ${KANA}
    env_file: .env.development
    entrypoint: ["scripts/wait-for-kanadb.sh"]
    command: "npx knex migrate:latest"

  backend-test:
    image: eggo-back
    profiles:
      - test
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    depends_on:
      eggo-devdb:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    env_file: .env.development
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src
    command: pnpm --filter=backend test

volumes:
  redis-data:
    driver: local
