services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:${BACKEND_VERSION}
    pull_policy: always
    depends_on:
      eggo-prod-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: eggo-prod-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      FRONTEND_URL: https://${HUB_PUBLIC_URL}
      BACKEND_URL: https://${HUB_PUBLIC_URL}
      REDIS_HOST: eggo-prod-redis
      REDIS_PORT: 6379
      STEAM_API_KEY: $STEAM_API_KEY
      FACEIT_API_KEY: $FACEIT_API_KEY
      OTEL_SERVICE_NAME: eggosystem-backend-1
      OTEL_SERVICE_NAMESPACE: eggosystem
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production,service.namespace=eggosystem,service.name=eggosystem-backend-1"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://alloy:4317"
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://alloy:4317"
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://alloy:4318/v1/logs"
      OTEL_EXPORTER_OTLP_PROFILING_ENDPOINT: "http://alloy:4040"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: "http/json"
      OTEL_EXPORTER_OTLP_PROFILING_REGION_TAG: production
      OTEL_EXPORTER_OTLP_PROFILING_VERSION_TAG: 1.0.0
      PRIVACY_POLICY_VERSION: $PRIVACY_POLICY_VERSION
      SMTP_HOST: $SMTP_HOST
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      ALLSTAR_WEBHOOK_TOKEN: $ALLSTAR_WEBHOOK_TOKEN
      ALLSTAR_API_KEY: $ALLSTAR_API_KEY
      DISCORD_CLIENT_ID: $DISCORD_CLIENT_ID
      DISCORD_CLIENT_SECRET: $DISCORD_CLIENT_SECRET
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      DISCORD_GUILD_ID: $DISCORD_GUILD_ID
      RABBITMQ_HOST: eggo-prod-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PROD_PASS}
      BACKEND_SERVICE_API_KEY: ${PROD_SERVICE_API_KEY}
      JWT_SECRET: $JWT_SECRET
      FACEIT_WEBHOOK_API_KEY: $FACEIT_WEBHOOK_API_KEY
      IMAGE_SERVICE_API_KEY: $IMG_API_KEY
      IMAGE_SERVICE_URL: https://$IMG_PROD_PUBLIC_URL
    networks:
      - web
    volumes:
      - ./public_access_token.pem:/usr/src/app/public_access_token.pem
      - ./public_refresh_token.pem:/usr/src/app/public_refresh_token.pem
      - ./private_access_token.pem:/usr/src/app/private_access_token.pem
      - ./private_refresh_token.pem:/usr/src/app/private_refresh_token.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbe.entrypoints=http"
      - "traefik.http.routers.hubbe.rule=Host(`${HUB_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.middlewares.hubbe-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hubbe.middlewares=hubbe-https-redirect"
      - "traefik.http.routers.hubbe-secure.entrypoints=https"
      - "traefik.http.routers.hubbe-secure.rule=Host(`${HUB_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.hubbe-secure.tls=true"
      - "traefik.http.routers.hubbe-secure.tls.domains[0].main=${HUB_PUBLIC_URL}"
      - "traefik.http.routers.hubbe-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbe-secure.service=hubbe"
      - "traefik.http.services.hubbe.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"
    restart: always

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend:${FRONTEND_VERSION}
    pull_policy: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_VIEWER_API_URL: https://${CS2D_PUBLIC_URL}
      NEXT_PUBLIC_API_URL: https://${HUB_PUBLIC_URL}
      NEXT_PUBLIC_CLIENT_API_URL: https://${HUB_PUBLIC_URL}
      NEXT_PUBLIC_BASE_URL: https://${HUB_PUBLIC_URL}
      NEXT_PUBLIC_IMAGE_SERVICE_URL: https://${IMG_PROD_PUBLIC_URL}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahub.entrypoints=http"
      - "traefik.http.routers.kanahub.rule=Host(`${HUB_PUBLIC_URL}`)"
      - "traefik.http.middlewares.kanahub-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanahub.middlewares=kanahub-https-redirect"
      - "traefik.http.routers.kanahub-secure.entrypoints=https"
      - "traefik.http.routers.kanahub-secure.rule=Host(`${HUB_PUBLIC_URL}`)"
      - "traefik.http.routers.kanahub-secure.tls=true"
      - "traefik.http.routers.kanahub-secure.tls.domains[0].main=${HUB_PUBLIC_URL}"
      - "traefik.http.routers.kanahub-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahub-secure.service=kanahub"
      - "traefik.http.services.kanahub.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    restart: always

  eggo-prod-db:
    image: mariadb:12.1.2
    container_name: eggo-prod-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-data/data:/var/lib/mysql

  eggo-prod-redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    networks:
      - web
    restart: always
    volumes:
      - redis-prod-data:/data

  migrations:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-migrations:${MIGRATIONS_VERSION}
    depends_on:
      eggo-prod-db:
        condition: service_healthy
    environment:
      DB_HOST: eggo-prod-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      WAIT_FOR_DB: ${KANA}
    entrypoint: ["scripts/wait-for-kanadb.sh"]
    command: "npx knex migrate:latest"
    networks:
      - web
    restart: no

  maxscale:
    image: mariadb/maxscale:24.02
    container_name: maxscale
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
      - ./maxscale-logs:/var/log/maxscale
    networks:
      - web
    restart: always

  phpmyadmin-hub:
    depends_on:
      - eggo-prod-db
    image: phpmyadmin/phpmyadmin:5.2.3
    restart: always
    environment:
      PMA_HOST: eggo-prod-db
      #PMA_HOST: maxscale
      #PMA_PORT: 4006
      PMA_ABSOLUTE_URI: https://${HUB_PUBLIC_URL}/mysadmin/
      UPLOAD_LIMIT: 1G
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin-hub.entrypoints=http"
      - "traefik.http.routers.phpmyadmin-hub.rule=Host(`hub.kanaliiga.fi`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.middlewares.phpmyadmin-hub-stripprefix.stripprefix.prefixes=/mysadmin"
      - "traefik.http.middlewares.phpmyadmin-hub-auth.basicauth.users=${PHPMYADMIN_AUTH}"
      - "traefik.http.middlewares.phpmyadmin-hub-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin-hub.middlewares=phpmyadmin-hub-https-redirect"
      - "traefik.http.routers.phpmyadmin-hub-secure.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-hub-secure.rule=Host(`hub.kanaliiga.fi`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.routers.phpmyadmin-hub-secure.tls=true"
      - "traefik.http.routers.phpmyadmin-hub-secure.tls.domains[0].main=hub.kanaliiga.fi"
      - "traefik.http.routers.phpmyadmin-hub-secure.tls.certresolver=http"
      - "traefik.http.routers.phpmyadmin-hub-secure.service=phpmyadmin-hub"
      - "traefik.http.routers.phpmyadmin-hub-secure.middlewares=phpmyadmin-hub-stripprefix,phpmyadmin-hub-auth"
      - "traefik.http.services.phpmyadmin-hub.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  eggo-db-backup:
    image: databack/mysql-backup
    restart: always
    depends_on:
      eggo-prod-db:
        condition: service_healthy
    environment:
      DB_USER: "root"
      DB_PASS: "${MARIADB_ROOT_PASSWORD}"
      DB_SERVER: "eggo-prod-db"
      DB_DUMP_TARGET: "/db"
      DB_DUMP_FREQUENCY: "1440"
      DB_DUMP_BEGIN: "0400"
      DB_CLEANUP_TIME: "7"
      COMPRESSION: "gzip"
    volumes:
      - ./db-backup:/db
    command: dump
    networks:
      - web

  eggo-prod-rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: eggo-prod-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PROD_PASS}
    networks:
      - web
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-prod-data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq-hub.entrypoints=http"
      - "traefik.http.routers.rabbitmq-hub.rule=Host(`hub-mq.kanaliiga.fi`)"
      - "traefik.http.middlewares.rabbitmq-hub-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rabbitmq-hub.middlewares=rabbitmq-hub-https-redirect"
      - "traefik.http.routers.rabbitmq-hub-secure.entrypoints=https"
      - "traefik.http.routers.rabbitmq-hub-secure.rule=Host(`hub-mq.kanaliiga.fi`)"
      - "traefik.http.routers.rabbitmq-hub-secure.tls=true"
      - "traefik.http.routers.rabbitmq-hub-secure.tls.domains[0].main=hub-mq.kanaliiga.fi"
      - "traefik.http.routers.rabbitmq-hub-secure.tls.certresolver=http"
      - "traefik.http.routers.rabbitmq-hub-secure.service=rabbitmq-hub"
      - "traefik.http.services.rabbitmq-hub.loadbalancer.server.port=15672"
      - "traefik.docker.network=web"

networks:
  web:
    external: true

volumes:
  mariadb_data:
    name: eggo_mariadb_data
  redis-prod-data:
    name: redis_prod_data
  rabbitmq-prod-data:
    name: rabbitmq_prod_data
