services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:${BACKEND_VERSION}
    pull_policy: always
    depends_on:
      eggo-stage-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: eggo-stage-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_STAGE_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      FRONTEND_URL: https://${HUBSTAGE_PUBLIC_URL}
      BACKEND_URL: https://${HUBSTAGE_PUBLIC_URL}
      REDIS_HOST: eggo-stage-redis
      REDIS_PORT: 6379
      STEAM_API_KEY: $STEAM_API_KEY
      FACEIT_API_KEY: $FACEIT_API_KEY
      OTEL_SERVICE_NAME: eggosystem-stage-backend-1
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=stage,service.namespace=eggosystem,service.version=1.0.0,service.instance.id=backend"
      PRIVACY_POLICY_VERSION: $PRIVACY_POLICY_VERSION
      SMTP_HOST: $SMTP_HOST
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      ALLSTAR_WEBHOOK_TOKEN: $ALLSTAR_WEBHOOK_TOKEN
      ALLSTAR_API_KEY: $ALLSTAR_API_KEY
      DISCORD_CLIENT_ID: $DISCORD_CLIENT_ID
      DISCORD_CLIENT_SECRET: $DISCORD_CLIENT_SECRET
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      DISCORD_GUILD_ID: $DISCORD_GUILD_ID
      RABBITMQ_HOST: eggo-stage-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_STAGE_PASS}
      BACKEND_SERVICE_API_KEY: ${STAGE_SERVICE_API_KEY}
    networks:
      - web
    volumes:
      - ./public_access_token.pem:/usr/src/app/public_access_token.pem
      - ./public_refresh_token.pem:/usr/src/app/public_refresh_token.pem
      - ./private_access_token.pem:/usr/src/app/private_access_token.pem
      - ./private_refresh_token.pem:/usr/src/app/private_refresh_token.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbestage.entrypoints=http"
      - "traefik.http.routers.hubbestage.rule=Host(`${HUBSTAGE_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.middlewares.hubbestage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hubbestage.middlewares=hubbestage-https-redirect"
      - "traefik.http.routers.hubbestage-secure.entrypoints=https"
      - "traefik.http.routers.hubbestage-secure.rule=Host(`${HUBSTAGE_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.hubbestage-secure.tls=true"
      - "traefik.http.routers.hubbestage-secure.tls.domains[0].main=${HUBSTAGE_PUBLIC_URL}"
      - "traefik.http.routers.hubbestage-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbestage-secure.service=hubbestage"
      - "traefik.http.services.hubbestage.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"
    restart: always

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend:${FRONTEND_VERSION}
    pull_policy: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://${HUBSTAGE_PUBLIC_URL}
      NEXT_PUBLIC_CLIENT_API_URL: https://${HUBSTAGE_PUBLIC_URL}
      NEXT_PUBLIC_BASE_URL: https://${HUBSTAGE_PUBLIC_URL}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahubstage.entrypoints=http"
      - "traefik.http.routers.kanahubstage.rule=Host(`${HUBSTAGE_PUBLIC_URL}`)"
      - "traefik.http.middlewares.kanahubstage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanahubstage.middlewares=kanahubstage-https-redirect"
      - "traefik.http.routers.kanahubstage-secure.entrypoints=https"
      - "traefik.http.routers.kanahubstage-secure.rule=Host(`${HUBSTAGE_PUBLIC_URL}`)"
      - "traefik.http.routers.kanahubstage-secure.tls=true"
      - "traefik.http.routers.kanahubstage-secure.tls.domains[0].main=${HUBSTAGE_PUBLIC_URL}"
      - "traefik.http.routers.kanahubstage-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahubstage-secure.service=kanahubstage"
      - "traefik.http.services.kanahubstage.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    restart: always

  eggo-stage-db:
    image: bitnami/mariadb:11.7.2
    container_name: eggo-stage-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_STAGE_ROOT_PASSWORD}"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: "${MARIADB_STAGE_PASSWORD}"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_STAGE_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10
    volumes:
      - ./my.cnf:/opt/bitnami/mariadb/conf/my.cnf
      - ./db-data:/bitnami/mariadb

  eggo-stage-redis:
    image: redis:8-alpine
    networks:
      - web
    restart: always

  phpmyadmin-hubstage:
    depends_on:
      - eggo-stage-db
    image: phpmyadmin/phpmyadmin:5.2.2
    restart: always
    environment:
      PMA_HOST: eggo-stage-db
      PMA_ABSOLUTE_URI: https://${HUBSTAGE_PUBLIC_URL}/mysadmin/
      UPLOAD_LIMIT: 1G
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin-hubstage.entrypoints=http"
      - "traefik.http.routers.phpmyadmin-hubstage.rule=Host(`${HUBSTAGE_PUBLIC_URL}`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.middlewares.phpmyadmin-hubstage-stripprefix.stripprefix.prefixes=/mysadmin"
      - "traefik.http.middlewares.phpmyadmin-hubstage-auth.basicauth.users=${PHPMYADMIN_AUTH}"
      - "traefik.http.middlewares.phpmyadmin-hubstage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin-hubstage.middlewares=phpmyadmin-hubstage-https-redirect"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.rule=Host(`${HUBSTAGE_PUBLIC_URL}`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.tls=true"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.tls.domains[0].main=${HUBSTAGE_PUBLIC_URL}"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.tls.certresolver=http"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.service=phpmyadmin-hubstage"
      - "traefik.http.routers.phpmyadmin-hubstage-secure.middlewares=phpmyadmin-hubstage-stripprefix,phpmyadmin-hubstage-auth"
      - "traefik.http.services.phpmyadmin-hubstage.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  eggo-migrations:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-migrations:${MIGRATIONS_VERSION}
    depends_on:
      eggo-stage-db:
        condition: service_healthy
    environment:
      DB_HOST: eggo-stage-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_STAGE_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      WAIT_FOR_DB: ${KANA}
    entrypoint: ["scripts/wait-for-kanadb.sh"]
    command: "npx knex migrate:latest"
    networks:
      - web
    restart: no

  eggo-stage-rabbitmq:
    image: rabbitmq:4.1-management
    container_name: eggo-stage-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_STAGE_PASS}
    networks:
      - web
    ports:
      - "5672:5672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq-hubstage.entrypoints=http"
      - "traefik.http.routers.rabbitmq-hubstage.rule=Host(`hubdev-mq.kanaliiga.fi`)"
      - "traefik.http.middlewares.rabbitmq-hubstage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rabbitmq-hubstage.middlewares=rabbitmq-hubstage-https-redirect"
      - "traefik.http.routers.rabbitmq-hubstage-secure.entrypoints=https"
      - "traefik.http.routers.rabbitmq-hubstage-secure.rule=Host(`hubdev-mq.kanaliiga.fi`)"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls=true"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls.domains[0].main=hubdev-mq.kanaliiga.fi"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls.certresolver=http"
      - "traefik.http.routers.rabbitmq-hubstage-secure.service=rabbitmq-hubstage"
      - "traefik.http.services.rabbitmq-hubstage.loadbalancer.server.port=15672"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
