services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:staging
    pull_policy: always
    depends_on:
      eggo-staging-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: eggo-staging-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      FRONTEND_URL: https://${HUBDEV_PUBLIC_URL}
      BACKEND_URL: https://${HUBDEV_PUBLIC_URL}
      REDIS_HOST: eggo-staging-redis
      REDIS_PORT: 6379
      STEAM_API_KEY: $STEAM_API_KEY
      JWT_SECRET: $JWT_SECRET_STAGING
      JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET_STAGING
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging,service.namespace=eggosystem,service.version=1.0.0.0,service.instance.id=backend"
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=${NEWRELIC_API_KEY}"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbedev.entrypoints=http"
      - "traefik.http.routers.hubbedev.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.middlewares.hubbestaging-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hubbedev.middlewares=hubbestaging-https-redirect"
      - "traefik.http.routers.hubbestaging-secure.entrypoints=https"
      - "traefik.http.routers.hubbestaging-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.hubbestaging-secure.tls=true"
      - "traefik.http.routers.hubbestaging-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.hubbestaging-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbestaging-secure.service=hubbedev"
      - "traefik.http.services.hubbedev.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend:staging
    pull_policy: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://${HUBDEV_PUBLIC_URL}
      NEXT_PUBLIC_CLIENT_API_URL: https://${HUBDEV_PUBLIC_URL}
      NEXT_PUBLIC_BASE_URL: https://${HUBDEV_PUBLIC_URL}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahubdev.entrypoints=http"
      - "traefik.http.routers.kanahubdev.rule=Host(`${HUBDEV_PUBLIC_URL}`)"
      - "traefik.http.middlewares.kanahubstaging-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanahubdev.middlewares=kanahubstaging-https-redirect"
      - "traefik.http.routers.kanahubstaging-secure.entrypoints=https"
      - "traefik.http.routers.kanahubstaging-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`)"
      - "traefik.http.routers.kanahubstaging-secure.tls=true"
      - "traefik.http.routers.kanahubstaging-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.kanahubstaging-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahubstaging-secure.service=kanahubdev"
      - "traefik.http.services.kanahubdev.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

  eggo-staging-db:
    image: bitnami/mariadb:11.4.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_MAX_ALLOWED_PACKET: 128M
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MARIADB_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10

  eggo-staging-redis:
    image: redis:7-alpine
    networks:
      - web
    restart: always

  phpmyadmin-hubdev:
    depends_on:
      - eggo-staging-db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: eggo-staging-db
      PMA_ABSOLUTE_URI: https://${HUBDEV_PUBLIC_URL}/mysadmin/
      UPLOAD_LIMIT: 1G
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin-hubdev.entrypoints=http"
      - "traefik.http.routers.phpmyadmin-hubdev.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.middlewares.phpmyadmin-hubstaging-stripprefix.stripprefix.prefixes=/mysadmin"
      - "traefik.http.middlewares.phpmyadmin-hubstaging-auth.basicauth.users=${PHPMYADMIN_AUTH}"
      - "traefik.http.middlewares.phpmyadmin-hubstaging-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin-hubdev.middlewares=phpmyadmin-hubstaging-https-redirect"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/mysadmin/`)"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.tls=true"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.tls.certresolver=http"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.service=phpmyadmin-hubdev"
      - "traefik.http.routers.phpmyadmin-hubstaging-secure.middlewares=phpmyadmin-hubstaging-stripprefix,phpmyadmin-hubstaging-auth"
      - "traefik.http.services.phpmyadmin-hubdev.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  eggo-migrations:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-migrations:staging
    depends_on:
      eggo-staging-db:
        condition: service_healthy
    environment:
      DB_HOST: eggo-staging-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
      WAIT_FOR_DB: ${KANA}
    entrypoint: ["scripts/wait-for-kanadb.sh"]
    command: ["npx", "knex", "migrate:latest", "--knexfile=knexfile.js"]
    networks:
      - web

networks:
  web:
    external: true
