services:
  backend:
    image: eggo-back
    container_name: eggo-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      eggo-devdb:
        condition: service_healthy
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src # Mount source code for live reloading
    env_file: "dev.env"
    command: 'pnpm --filter=backend dev'

  frontend:
    image: eggo-front
    container_name: eggo-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["node", "./apps/frontend/server.js"]

  eggo-redis:
    image: redis:7-alpine
    restart: always
    container_name: eggo-redis

  eggo-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eggo-phpmyadmin
    depends_on:
      eggo-devdb:
        condition: service_healthy
    ports:
      - 8082:80
    restart: always
    environment:
      PMA_HOST: eggo-devdb
      MYSQL_ROOT_PASSWORD: dev-pass
      UPLOAD_LIMIT: 1G

  eggo-devdb:
    image: bitnami/mariadb:11.4.2
    restart: always
    container_name: eggo-devdb
    # If you need to access from own host with some other tool
    # ports:
    #   - 6666:3306
    environment:
      - MARIADB_ROOT_PASSWORD=dev-pass
      - MARIADB_USER=kanadbuser
      - MARIADB_PASSWORD=dev-pass
      - MARIADB_DATABASE=kanaliiga
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    volumes:
      # - ./apps/backend/dbdump/kanaliiga.sql:/docker-entrypoint-initdb.d/dump.sql -- For production migration...
      - ./apps/backend/seeds/dev/kana_dev_test_seed.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MARIADB_ROOT_PASSWORD']
      timeout: 20s
      retries: 10

  # migrations:
  #   container_name: be_migrations
  #   image: eggo-back
  #   build:
  #     context: .
  #     dockerfile: ./apps/backend/Dockerfile.dev
  #   depends_on:
  #     eggo-devdb:
  #       condition: service_healthy
  #   environment: *env
  #   working_dir: /usr/src/app/apps/backend
  #   ports:
  #     - 8485:3000
  #   volumes:
  #     - ./apps/dbdump:/usr/src/app/dbdump
  #   command: 'pnpm --filter=backend migrate'

  backend-test:
    container_name: eggo-back-test
    image: eggo-back
    build:
      context: .
      dockerfile:  ./apps/backend/Dockerfile.dev
    depends_on:
      eggo-devdb:
        condition: service_healthy
      # migrations:
      #   condition: service_completed_successfully
    env_file: "dev.env"
    volumes:
      - ./apps/backend/src:/usr/src/app/apps/backend/src
    # ports:
    #   - '8283:8080'
    command: pnpm --filter=backend test
