services:
  # backend:
  #   build:
  #     context: ./apps/backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   command: ["pnpm", "start"]

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]
