services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:dev
    depends_on:
      eggo-dev-db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: eggo-dev-db
      DB_USER: kanadbuser
      DB_PASSWORD: "dev-pass"
      DB_NAME: kanaliiga
      DB_PORT: 3306
      FRONTEND_URL: https://${HUBDEV_PUBLIC_URL}
      REDIS_HOST: eggo-redis
      REDIS_PORT: 6379
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbe-dev.entrypoints=http"
      - "traefik.http.routers.hubbe-dev.rule=Host(`${HUBBEDEV_PUBLIC_URL}`)"
      - "traefik.http.middlewares.hubbe-dev-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hubbe-dev.middlewares=kanahub-dev-https-redirect"
      - "traefik.http.routers.hubbe-dev-secure.entrypoints=https"
      - "traefik.http.routers.hubbe-dev-secure.rule=Host(`${HUBBEDEV_PUBLIC_URL}`)"
      - "traefik.http.routers.hubbe-dev-secure.tls=true"
      - "traefik.http.routers.hubbe-dev-secure.tls.domains[0].main=${HUBBEDEV_PUBLIC_URL}"
      - "traefik.http.routers.hubbe-dev-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbe-dev-secure.service=hubbe-dev"
      - "traefik.http.services.hubbe-dev.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend:dev
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_URL: https://${HUBDEV_PUBLIC_URL}/
      NEXT_PUBLIC_API_URL: https://${HUBBEDEV_PUBLIC_URL}/
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahub-dev.entrypoints=http"
      - "traefik.http.routers.kanahub-dev.rule=Host(`${HUBDEV_PUBLIC_URL}`)"
      - "traefik.http.middlewares.kanahub-dev-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanahub-dev.middlewares=kanahub-dev-https-redirect"
      - "traefik.http.routers.kanahub-dev-secure.entrypoints=https"
      - "traefik.http.routers.kanahub-dev-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`)"
      - "traefik.http.routers.kanahub-dev-secure.tls=true"
      - "traefik.http.routers.kanahub-dev-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.kanahub-dev-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahub-dev-secure.service=kanahub-dev"
      - "traefik.http.services.kanahub-dev.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

  eggo-dev-db:
    image: bitnami/mariadb:11.4.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "dev-pass"
      MARIADB_USER: kanadbuser
      MARIADB_PASSWORD: "dev-pass"
      MARIADB_DATABASE: kanaliiga
      MARIADB_MAX_ALLOWED_PACKET: 128M
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pdev-pass"
        ]
      timeout: 20s
      retries: 10

  eggo-redis:
    image: redis:7-alpine
    restart: always
    networks:
      - web

  migrate:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:devseed
    environment:
      DB_HOST: eggo-dev-db
      DB_PORT: 3306
      DB_USER: kanadbuser
      DB_PASSWORD: dev-pass
      DB_ROOT_PASSWORD: dev-pass
      DB_NAME: kanaliiga
    profiles:
      - migrate
    depends_on:
      eggo-dev-db:
        condition: service_healthy
    command: "pnpm migrate"

  seed:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend:devseed
    profiles:
      - seed
    environment:
      DB_HOST: eggo-dev-db
      DB_PORT: 3306
      DB_USER: kanadbuser
      DB_PASSWORD: dev-pass
      DB_ROOT_PASSWORD: dev-pass
      DB_NAME: kanaliiga
    depends_on:
      eggo-dev-db:
        condition: service_healthy
    command: "pnpm seed"

networks:
  web:
    external: true
