services:
  eggo-stage-backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - eggo-stage-redis
      - eggo-stage-db
    environment:
      NODE_ENV: production
      PORT: 3001
      MYSQL_HOST: eggo-stage-db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: eggo-stage-redis
      REDIS_PORT: 6379
      STEAM_API_KEY: $STEAM_API_KEY
      FACEIT_API_KEY: $FACEIT_API_KEY
      OTEL_SERVICE_NAME: eggosystem-stage-backend-1
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=stage,service.namespace=eggosystem,service.version=1.0.0,service.instance.id=backend"
      PRIVACY_POLICY_VERSION: $PRIVACY_POLICY_VERSION
      SMTP_HOST: $SMTP_HOST
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      ALLSTAR_WEBHOOK_TOKEN: $ALLSTAR_WEBHOOK_TOKEN
      ALLSTAR_API_KEY: $ALLSTAR_API_KEY
      DISCORD_CLIENT_ID: $DISCORD_CLIENT_ID
      DISCORD_CLIENT_SECRET: $DISCORD_CLIENT_SECRET
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      DISCORD_GUILD_ID: $DISCORD_GUILD_ID
      RABBITMQ_HOST: eggo-stage-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_STAGE_PASS}
      BACKEND_SERVICE_API_KEY: ${STAGE_SERVICE_API_KEY}
      JWT_SECRET: $JWT_SECRET
      FACEIT_WEBHOOK_API_KEY: $FACEIT_WEBHOOK_API_KEY
    networks:
      - web

  eggo-stage-frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - eggo-stage-backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_CLIENT_API_URL: ${NEXT_PUBLIC_CLIENT_API_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    networks:
      - web

  eggo-stage-db:
    image: bitnami/mariadb:11.7.2
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/bitnami/mariadb
    networks:
      - web

  eggo-stage-redis:
    image: redis:8-alpine
    restart: always
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - web

  eggo-stage-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    restart: always
    depends_on:
      - eggo-stage-db
    environment:
      - PMA_HOST=eggo-stage-db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - web
    restart: no

  eggo-stage-rabbitmq:
    image: rabbitmq:4.1-management
    container_name: eggo-stage-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_STAGE_PASS}
    networks:
      - web
    ports:
      - "5672:5672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq-hubstage.entrypoints=http"
      - "traefik.http.routers.rabbitmq-hubstage.rule=Host(`hubdev-mq.kanaliiga.fi`)"
      - "traefik.http.middlewares.rabbitmq-hubstage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rabbitmq-hubstage.middlewares=rabbitmq-hubstage-https-redirect"
      - "traefik.http.routers.rabbitmq-hubstage-secure.entrypoints=https"
      - "traefik.http.routers.rabbitmq-hubstage-secure.rule=Host(`hubdev-mq.kanaliiga.fi`)"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls=true"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls.domains[0].main=hubdev-mq.kanaliiga.fi"
      - "traefik.http.routers.rabbitmq-hubstage-secure.tls.certresolver=http"
      - "traefik.http.routers.rabbitmq-hubstage-secure.service=rabbitmq-hubstage"
      - "traefik.http.services.rabbitmq-hubstage.loadbalancer.server.port=15672"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
