services:
  backend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-backend
    depends_on:
      eggo-prod-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: eggo-prod-db
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: "${MARIADB_PASSWORD}"
      DB_NAME: ${MARIADB_DATABASE}
      DB_PORT: 3306
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubbe.entrypoints=http"
      - "traefik.http.routers.hubbe.rule=Host(`${HUBBE_PUBLIC_URL}`)"
      - "traefik.http.middlewares.hubbe-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hubbe.middlewares=kanahub-https-redirect"
      - "traefik.http.routers.hubbe-secure.entrypoints=https"
      - "traefik.http.routers.hubbe-secure.rule=Host(`${HUBBE_PUBLIC_URL}`)"
      - "traefik.http.routers.hubbe-secure.tls=true"
      - "traefik.http.routers.hubbe-secure.tls.domains[0].main=${HUBBE_PUBLIC_URL}"
      - "traefik.http.routers.hubbe-secure.tls.certresolver=http"
      - "traefik.http.routers.hubbe-secure.service=hubbe"
      - "traefik.http.services.hubbe.loadbalancer.server.port=3001"
      - "traefik.docker.network=web"

  frontend:
    image: registry.gitlab.com/kanaliiga_public/kanahub/eggosystem/eggo-frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: http://${HUB_PUBLIC_URL}/
      NEXT_PUBLIC_API_URL: http://${HUBBE_PUBLIC_URL}/
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanahub.entrypoints=http"
      - "traefik.http.routers.kanahub.rule=Host(`${HUB_PUBLIC_URL}`)"
      - "traefik.http.middlewares.kanahub-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanahub.middlewares=kanahub-https-redirect"
      - "traefik.http.routers.kanahub-secure.entrypoints=https"
      - "traefik.http.routers.kanahub-secure.rule=Host(`${HUB_PUBLIC_URL}`)"
      - "traefik.http.routers.kanahub-secure.tls=true"
      - "traefik.http.routers.kanahub-secure.tls.domains[0].main=${HUB_PUBLIC_URL}"
      - "traefik.http.routers.kanahub-secure.tls.certresolver=http"
      - "traefik.http.routers.kanahub-secure.service=kanahub"
      - "traefik.http.services.kanahub.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

  eggo-prod-db:
    image: bitnami/mariadb:11.4.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_MAX_ALLOWED_PACKET: 128M
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
    networks:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MARIADB_ROOT_PASSWORD"
        ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      eggo-prod-db:
        condition: service_healthy
    restart: always
    environment:
      PMA_HOST: eggo-prod-db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 1G
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hubphpmyadmin.entrypoints=http"
      - "traefik.http.routers.hubphpmyadmin.rule=Host(`${HUBDEV_PUBLIC_URL}`) && PathPrefix(`/phpmyadmin`)"
      - "traefik.http.middlewares.hubphpmyadmin-auth.basicauth.users=${PHPMYADMIN_AUTH}"
      - "traefik.http.middlewares.hubphpmyadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.hubphpmyadmin-stripprefix.stripprefix.prefixes=/phpmyadmin"
      - "traefik.http.routers.hubphpmyadmin.middlewares=hubphpmyadmin-https-redirect"
      - "traefik.http.routers.hubphpmyadmin-secure.entrypoints=https"
      - "traefik.http.routers.hubphpmyadmin-secure.rule=Host(`${HUBDEV_PUBLIC_URL}`)"
      - "traefik.http.routers.hubphpmyadmin-secure.tls=true"
      - "traefik.http.routers.hubphpmyadmin-secure.tls.domains[0].main=${HUBDEV_PUBLIC_URL}"
      - "traefik.http.routers.hubphpmyadmin-secure.middlewares=hubphpmyadmin-stripprefix,hubphpmyadmin-auth"
      - "traefik.http.routers.hubphpmyadmin-secure.tls.certresolver=http"
      - "traefik.http.routers.hubphpmyadmin-secure.service=hubphpmyadmin"
      - "traefik.http.services.hubphpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
