# Base image
FROM node:22-slim@sha256:ec318fe0dc46b56bcc1ca42a202738aeb4f3e347a7b4dd9f9f1df12ea7aa385a
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN npm install -g pnpm

# Copy dependency files first
COPY pnpm-workspace.yaml turbo.json ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/*/package.json ./packages/

# Install dependencies
ARG CI=false
RUN if [ "${CI}" = "true" ]; then \
      pnpm config set registry http://172.17.0.1:4873; \
    fi
RUN pnpm install --filter='!backend' --frozen-lockfile

# Copy source code after dependency installation
COPY packages/ ./packages/
COPY apps/frontend/ ./apps/frontend/

# Expose the port
EXPOSE 3000
ENV PORT=3000

# Start Next.js server
CMD [ "pnpm", "--filter=frontend", "dev" ]
