# Base image
FROM node:25-slim@sha256:34d76bac75fba8eea764d3b79b05be7a77fa0651d7b956b011b4a55837fdbc02
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN npm install -g pnpm

# Copy dependency files first
COPY pnpm-workspace.yaml turbo.json ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/*/package.json ./packages/

# Install dependencies
ARG CI=false
RUN if [ "${CI}" = "true" ]; then \
  pnpm config set registry http://172.17.0.1:4873; \
  fi
RUN pnpm install --filter='!backend' --frozen-lockfile

# Copy source code after dependency installation
COPY packages/ ./packages/
COPY apps/frontend/ ./apps/frontend/

# Add environment variables for version tracking
ARG NEXT_PUBLIC_API_URL=https://hubdev.kanaliiga.fi
ARG NEXT_PUBLIC_VIEWER_API_URL=https://cs2ddev.kanaliiga.fi
ARG NEXT_PUBLIC_CLIENT_API_URL=https://hubdev.kanaliiga.fi
ARG NEXT_PUBLIC_BASE_URL=https://hubdev.kanaliiga.fi
ARG NEXT_PUBLIC_IMAGE_SERVICE_URL=https://imgdev.kanaliiga.fi
ARG NEXT_PUBLIC_GIT_SHA
ARG NEXT_PUBLIC_GITLAB_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_VIEWER_API_URL=${NEXT_PUBLIC_VIEWER_API_URL}
ENV NEXT_PUBLIC_CLIENT_API_URL=${NEXT_PUBLIC_CLIENT_API_URL}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_IMAGE_SERVICE_URL=${NEXT_PUBLIC_IMAGE_SERVICE_URL}
ENV NEXT_PUBLIC_GIT_SHA=${NEXT_PUBLIC_GIT_SHA}
ENV NEXT_PUBLIC_GITLAB_URL=${NEXT_PUBLIC_GITLAB_URL}

# Build types package
RUN pnpm i --filter=@eggosystem/types
RUN pnpm build --filter=@eggosystem/types

# Expose the port
EXPOSE 3000
ENV PORT=3000

# Start Next.js server
CMD [ "pnpm", "--filter=frontend", "dev" ]
