# Base image
FROM node:22-slim
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN npm install -g pnpm

# Copy dependency files first
COPY pnpm-workspace.yaml turbo.json ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/*/package.json ./packages/

# Install dependencies
RUN pnpm install --filter='!backend' --frozen-lockfile

# Copy source code after dependency installation
COPY packages/ ./packages/
COPY apps/frontend/ ./apps/frontend/

# Expose the port
EXPOSE 3000
ENV PORT=3000

# Start Next.js server
CMD [ "pnpm", "--filter=frontend", "dev" ]
