# Base image
FROM node:25-slim@sha256:34d76bac75fba8eea764d3b79b05be7a77fa0651d7b956b011b4a55837fdbc02 AS base
RUN apt-get update && apt-get install -y default-mysql-client

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY scripts/wait-for-kanadb.sh ./scripts/wait-for-kanadb.sh
RUN chmod +x ./scripts/wait-for-kanadb.sh
COPY apps/backend/knexfile.ts ./knexfile.ts
COPY apps/backend/migrations/ ./migrations/
COPY apps/backend/migrations/tsconfig.knex.json ./tsconfig.json

RUN npm install ts-node knex mysql2

CMD [ "node", "node_modules/.bin/knex", "migrate:latest" ]
