# Base image
FROM node:25-slim@sha256:5aea649bacdc35e8e20571131c4f3547477dfe66e677d45c005af6dbd1edfaa7 AS base
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN npm install -g pnpm

# Copy dependency files first
COPY pnpm-workspace.yaml turbo.json ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/*/package.json ./packages/

# Install dependencies
ARG CI=false
RUN if [ "${CI}" = "true" ]; then \
      pnpm config set registry http://172.17.0.1:4873; \
    fi
RUN pnpm install --frozen-lockfile

# Copy source code after dependency installation
COPY packages/ ./packages/
COPY apps/backend/ ./apps/backend/

# Build types package
RUN pnpm i --filter=@eggosystem/types
RUN pnpm build --filter=@eggosystem/types

EXPOSE 3001
CMD [ "pnpm", "--filter=backend", "dev" ]
