# Base image
FROM node:25-slim@sha256:b20f82c2332a22609edb43cdfd6b16cbb199a6e6fd5cf8d5ef85b43faab43144 AS base
RUN apt-get update && apt-get install -y default-mysql-client

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY scripts/wait-for-kanadb.sh ./scripts/wait-for-kanadb.sh
RUN chmod +x ./scripts/wait-for-kanadb.sh
COPY apps/backend/knexfile.ts ./knexfile.ts
COPY apps/backend/migrations/ ./migrations/
COPY apps/backend/migrations/tsconfig.knex.json ./tsconfig.json

RUN npm install ts-node knex mysql2

CMD [ "node", "node_modules/.bin/knex", "migrate:latest" ]
