FROM node:25-slim@sha256:44bcbf493408a824104e74976ae5539f596c46cbe75ed0423a137552a555e2de AS builder
RUN apt-get update && apt-get install -y default-mysql-client

WORKDIR /usr/src/app

# Copy Knex configuration and migration files
COPY apps/backend/knexfile.ts ./knexfile.ts
COPY apps/backend/migrations/ ./migrations/
COPY apps/backend/migrations/tsconfig.knex.json ./tsconfig.json

# Install dependencies
RUN npm install ts-node knex mysql2 typescript

RUN npx tsc --project tsconfig.json

FROM node:25-slim@sha256:44bcbf493408a824104e74976ae5539f596c46cbe75ed0423a137552a555e2de AS production
RUN apt-get update && apt-get install -y default-mysql-client

ENV NODE_ENV=production
WORKDIR /usr/src/app

# Copy migration script
COPY scripts/wait-for-kanadb.sh ./scripts/wait-for-kanadb.sh
RUN chmod +x ./scripts/wait-for-kanadb.sh

# Copy compiled migrations and knexfile.js from builder
COPY --from=builder /usr/src/app/migrations/ ./migrations/
COPY --from=builder /usr/src/app/knexfile.js ./knexfile.js

# Install only production dependencies
RUN npm install knex mysql2

# Run migrations on startup
CMD ["node", "node_modules/.bin/knex", "--knexfile=knexfile.js", "migrate:latest"]
