FROM node:22-slim@sha256:157c7ea6f8c30b630d6f0d892c4f961eab9f878e88f43dd1c00514f95ceded8a AS builder
RUN apt-get update && apt-get install -y default-mysql-client

WORKDIR /usr/src/app

# Copy Knex configuration and migration files
COPY apps/backend/knexfile.ts ./knexfile.ts
COPY apps/backend/migrations/ ./migrations/
COPY apps/backend/migrations/tsconfig.knex.json ./tsconfig.json

# Install dependencies
RUN npm install ts-node knex mysql2 typescript

RUN npx tsc --project tsconfig.json

FROM node:22-slim@sha256:157c7ea6f8c30b630d6f0d892c4f961eab9f878e88f43dd1c00514f95ceded8a AS production
RUN apt-get update && apt-get install -y default-mysql-client

ENV NODE_ENV=production
WORKDIR /usr/src/app

# Copy migration script
COPY scripts/wait-for-kanadb.sh ./scripts/wait-for-kanadb.sh
RUN chmod +x ./scripts/wait-for-kanadb.sh

# Copy compiled migrations and knexfile.js from builder
COPY --from=builder /usr/src/app/migrations/ ./migrations/
COPY --from=builder /usr/src/app/knexfile.js ./knexfile.js

# Install only production dependencies
RUN npm install knex mysql2

# Run migrations on startup
CMD ["node", "node_modules/.bin/knex", "--knexfile=knexfile.js", "migrate:latest"]
