# Base image
FROM node:22-slim@sha256:f9f7f95dcf1f007b007c4dcd44ea8f7773f931b71dc79d57c216e731c87a090b AS base
RUN apt-get update && apt-get install -y default-mysql-client

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY scripts/wait-for-kanadb.sh ./scripts/wait-for-kanadb.sh
RUN chmod +x ./scripts/wait-for-kanadb.sh
COPY apps/backend/knexfile.ts ./knexfile.ts
COPY apps/backend/migrations/ ./migrations/
COPY apps/backend/migrations/tsconfig.knex.json ./tsconfig.json

RUN npm install ts-node knex mysql2

CMD [ "node", "node_modules/.bin/knex", "migrate:latest" ]
