services:
  devcontainer:
    build: .
    container_name: devcontainer
    volumes:
      - ..:/workspace
    env_file: "../.env.development"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001 # Override frontend API URL
    command: sleep infinity
    networks:
      - eggo-dev

  eggo-devdb:
    extends:
      file: ../docker-compose.yml
      service: eggo-devdb
    networks:
      - eggo-dev

  eggo-phpmyadmin:
    extends:
      file: ../docker-compose.yml
      service: eggo-phpmyadmin-dev
    networks:
      - eggo-dev
    ports:
      - 8083:80

  eggo-redis:
    extends:
      file: ../docker-compose.yml
      service: eggo-redis
    networks:
      - eggo-dev

  seed:
    extends:
      file: ../docker-compose.yml
      service: seed
    profiles: []
    networks:
      - eggo-dev

  migrations:
    extends:
      file: ../docker-compose.yml
      service: migrations
    profiles: []
    networks:
      - eggo-dev

networks:
  eggo-dev:
