services:
  devcontainer:
    build: .
    container_name: devcontainer
    volumes:
      - ..:/workspace
    env_file: "../.env.development"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001 # Override frontend API URL
    command: sleep infinity
    networks:
      - eggo-dev

  eggo-devdb:
    extends:
      file: ../docker-compose.yml
      service: eggo-devdb
    networks:
      - eggo-dev

  eggo-phpmyadmin:
    extends:
      file: ../docker-compose.yml
      service: eggo-phpmyadmin-dev
    networks:
      - eggo-dev
    ports:
      - 8083:80

  eggo-redis:
    extends:
      file: ../docker-compose.yml
      service: eggo-redis
    networks:
      - eggo-dev

  seed:
    image: eggo-back
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile.dev
    depends_on:
      eggo-devdb:
        condition: service_healthy
    env_file: ../.env.development
    command: "pnpm --filter=backend seed"
    networks:
      - eggo-dev

  migrate:
    image: eggo-back
    profiles:
      - migrate
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile.dev
    depends_on:
      eggo-devdb:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    env_file: ../.env.development
    command: "pnpm --filter=backend migrate"
    networks:
      - eggo-dev

networks:
  eggo-dev:
